### PR TITLE
Glassboii

### PR DESCRIPTION
**Pull request by reaves-tyler**

### CODE REVIEW

**Comment by Doug-Murphy** [comment]
I don't think this should have been merged. Bytes to MB isn't 10,000:1 and bytes to GB isn't 100,000:1. This ratios are wrong. They sold be 1,000,000:1 for MiB and 1,000,000:1 for GiB.

**Comment by reaves-tyler** [comment]
> They sold be 1,000,000:1 for MiB and 1,000,000:1 for GiB.

I'm a little confused on the meaning of this.  Would you like to Revert this?

**Comment by Doug-Murphy** [comment]
Autocorrect issue. They should*

Yes I would revert. The ratios are wrong. Mega = million. Giga = billion.

**Comment by Doug-Murphy** [comment]
Also, I don't see any truncation. Should we truncate to two decimal places when converting up from raw bytes?

**Comment by Doug-Murphy** [comment]
Oh and if there is no conversion required (bytes length <=3) then you aren't appending B.

**Comment by Joshua-Brent-Collins** [comment]
This goes back to process concerns. In general we don't want to self merge PRs even with approval. I think a good solution is to have a quorum of approvals for any given PR and then the last approver will merge. This is similar to how we do it at work and allows more 👀 on code. I know a lot of places uses the "you wrote it you merge it approach" so it will just take a little time adjusting. To help with this I added branch protection rules that will require 2 approvals.

**Comment by reaves-tyler** [comment]
Will revert and merge with further branch commits.

**Pull request merged**
